### PR TITLE
bump min rails dependency

### PR DESCRIPTION
**Pull request by georgesheppardbanked**
Rails 6.1 was released yesterday, specifying <. 6.1 means we're unable to upgrade. Tests pass with 6.1.

### CODE REVIEW

**Review by jturkel — CHANGES_REQUESTED** [review]
Thanks for the PR. Can you add Rails 6.1 to the CircleCI build matrix too?

**Comment by jturkel** [comment]
@georgesheppardbanked - Looks like our CircleCI configuration wasn't running builds for PRs from forks. Can you push another commit to trigger a build?

**Comment by georgesheppardbanked** [comment]
> @georgesheppardbanked - Looks like our CircleCI configuration wasn't running builds for PRs from forks. Can you push another commit to trigger a build?

Yep! just pushed an empty. commit to trigger Circle 🤞

**Review by jturkel — APPROVED** [review]
Thanks @georgesheppardbanked! I'll get a release out after I land https://github.com/salsify/avromatic/pull/129.

**Comment by georgesheppardbanked** [comment]
Thanks @jturkel

**Comment by jturkel** [comment]
Released in 2.3.0. Thanks again @georgesheppardbanked. 🎉

**Pull request merged**
